version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@02.2.1

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
          family: "${EXISTING_AWS_TASK_DEFINITION_NAME}"
          cluster-name: "${AWS_CLUSTER}"
          container-image-name-updates: "container=${EXISTING_AWS_TASK_DEFINITION_NAME},tag=${CIRCLE_SHA1}"


